name: 'Estimate PR Review Time'
description: 'Estimates PR review time and applies labels based on changes'
author: 'José Bonnet, Republic Europe'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  repository:
    description: 'Full repository name (e.g., user/repo)'
    required: true
  date_range:
    description: 'Date range to analyse'
    required: false
    default: '30d'
  pr_number:
    description: 'Pull request number'
    required: false
  config_path:
    required: false
    default: '.pr-review-config.yml'
  script_name:
    required: true  # to pick which script to run
    description: "Which script to run (must be in /bin/)"
    default: "estimator.sh"
    options:
      - analytics.sh
      - estimator.sh

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Run script
      run: |
        GITHUB_TOKEN=${{ inputs.github_token }} \
        REPOSITORY=${{ inputs.repository }} \
        PR_NUMBER=${{ inputs.pr_number }} \
        DATE_RANGE=${{ inputs.date_range }} \
        CONFIG_PATH=${{ inputs.config_path }} \
        bin/${{ inputs.script_name }}
